<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class ProductionSyncSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();

        $ticketColumns = Schema::getColumnListing('tickets');
        $userColumns = Schema::getColumnListing('users');
        $replyColumns = Schema::getColumnListing('ticket_replies');
        $notifColumns = Schema::getColumnListing('app_notifications');

        $users = array (
  0 => 
  array (
    'id' => 1,
    'name' => 'Admin',
    'email' => 'admin@gmail.com',
    'email_verified_at' => NULL,
    'password' => '$2y$12$ULCyIvIZePO3493/E0z1wOjGN4k0pX7oPpS0InlXmSOBGdKfbkruy',
    'role' => 'admin',
    'remember_token' => NULL,
    'created_at' => '2026-08-13T09:50:51.000000Z',
    'updated_at' => '2026-08-13T09:51:25.000000Z',
    'deleted_at' => NULL,
  ),
  1 => 
  array (
    'id' => 2,
    'name' => 'Agent',
    'email' => 'agent@gmail.com',
    'email_verified_at' => NULL,
    'password' => '$2y$12$F.QK7JwMabWkbKs7p..NnOrzA3K101.SjNWs4IqwMMwZihDM3NA7e',
    'role' => 'agent',
    'remember_token' => NULL,
    'created_at' => '2026-08-13T09:50:52.000000Z',
    'updated_at' => '2026-08-13T09:51:25.000000Z',
    'deleted_at' => NULL,
  ),
  2 => 
  array (
    'id' => 3,
    'name' => 'Ai',
    'email' => 'ai@system.local',
    'email_verified_at' => NULL,
    'password' => '$2y$12$g1pXwdnyN/95YxlBQRYepu1QUM8rJWfO1rHE3OSv7pwxcMIy4mooq',
    'role' => 'agent',
    'remember_token' => NULL,
    'created_at' => '2026-08-13T09:50:52.000000Z',
    'updated_at' => '2026-08-13T09:51:26.000000Z',
    'deleted_at' => NULL,
  ),
  3 => 
  array (
    'id' => 4,
    'name' => 'Kundan Rai',
    'email' => 'kundanrai8102002@gmail.com',
    'email_verified_at' => NULL,
    'password' => '$2y$12$tiKnRdv0Uy5AeM0TPf2VGee7Rr1pthxG.Z0ktUNIluB/fFSCWho1O',
    'role' => 'customer',
    'remember_token' => NULL,
    'created_at' => '2026-08-13T09:50:52.000000Z',
    'updated_at' => '2026-08-13T09:51:26.000000Z',
    'deleted_at' => NULL,
  ),
  4 => 
  array (
    'id' => 5,
    'name' => 'Rajat Nishad',
    'email' => 'rajatdiamondn@gmail.com',
    'email_verified_at' => NULL,
    'password' => '$2y$12$LSpZI0TBbWRlN0zjgrTA0urbSS1HYRV8VRdCe/ThkZ5kzzjjJrHpa',
    'role' => 'customer',
    'remember_token' => NULL,
    'created_at' => '2026-08-13T09:50:52.000000Z',
    'updated_at' => '2026-08-13T09:51:26.000000Z',
    'deleted_at' => NULL,
  ),
  5 => 
  array (
    'id' => 6,
    'name' => 'Shivam Rai',
    'email' => 'raishivamrai837@gmail.com',
    'email_verified_at' => NULL,
    'password' => '$2y$12$0nk7zbKffXeMObfr3EnAW.d0OortO52XAAVaCy4mvoDUMHE.cjGcC',
    'role' => 'customer',
    'remember_token' => NULL,
    'created_at' => '2026-08-13T09:50:53.000000Z',
    'updated_at' => '2026-08-13T09:51:26.000000Z',
    'deleted_at' => NULL,
  ),
  6 => 
  array (
    'id' => 7,
    'name' => 'Rajnish Ray',
    'email' => 'rayrb.1234@gmail.com',
    'email_verified_at' => NULL,
    'password' => '$2y$12$3/MZBGqxrw.L0z7wbT.qLes2zrFm/wt/OlBRHYIPE1W8B4wVbFqwW',
    'role' => 'customer',
    'remember_token' => NULL,
    'created_at' => '2026-08-13T09:50:53.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'deleted_at' => NULL,
  ),
  7 => 
  array (
    'id' => 8,
    'name' => 'Sarah Connor',
    'email' => 'sarah.connor@example.com',
    'email_verified_at' => NULL,
    'password' => '$2y$12$SKOxs/AYDCgx5qTvCnRcZu/IiOXQzvl8QrIqQPlmOThCG4GJiR5Va',
    'role' => 'customer',
    'remember_token' => NULL,
    'created_at' => '2026-08-13T09:50:53.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'deleted_at' => NULL,
  ),
);
        $tickets = array (
  0 => 
  array (
    'id' => 1,
    'sender_email' => 'kundanrai8102002@gmail.com',
    'sender_name' => 'Kundan Rai',
    'subject' => 'Payment done but bill is still pending (#101)',
    'body' => 'Hello support team,

I am facing an issue regarding: Payment done but bill is still pending (#101). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'technical support',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-07-31T07:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  1 => 
  array (
    'id' => 2,
    'sender_email' => 'rajatdiamondn@gmail.com',
    'sender_name' => 'Rajat Nishad',
    'subject' => 'In your site I have face some glitches (#102)',
    'body' => 'Hello support team,

I am facing an issue regarding: In your site I have face some glitches (#102). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'bug report',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-01T05:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  2 => 
  array (
    'id' => 3,
    'sender_email' => 'raishivamrai837@gmail.com',
    'sender_name' => 'Shivam Rai',
    'subject' => 'Test for attachments (#103)',
    'body' => 'Hello support team,

I am facing an issue regarding: Test for attachments (#103). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'refund request',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-02T03:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  3 => 
  array (
    'id' => 4,
    'sender_email' => 'rayrb.1234@gmail.com',
    'sender_name' => 'Rajnish Ray',
    'subject' => 'General issue with account login (#104)',
    'body' => 'Hello support team,

I am facing an issue regarding: General issue with account login (#104). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'account',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-03T01:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  4 => 
  array (
    'id' => 5,
    'sender_email' => 'sarah.connor@example.com',
    'sender_name' => 'Sarah Connor',
    'subject' => 'Refund request for order #8492 (#105)',
    'body' => 'Hello support team,

I am facing an issue regarding: Refund request for order #8492 (#105). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'general question',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-03T23:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  5 => 
  array (
    'id' => 6,
    'sender_email' => 'kundanrai8102002@gmail.com',
    'sender_name' => 'Kundan Rai',
    'subject' => 'Server connection timeout during checkout (#106)',
    'body' => 'Hello support team,

I am facing an issue regarding: Server connection timeout during checkout (#106). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'technical question',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-04T21:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  6 => 
  array (
    'id' => 7,
    'sender_email' => 'rajatdiamondn@gmail.com',
    'sender_name' => 'Rajat Nishad',
    'subject' => 'Technical Question regarding API authentication (#107)',
    'body' => 'Hello support team,

I am facing an issue regarding: Technical Question regarding API authentication (#107). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'feature request',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-05T19:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  7 => 
  array (
    'id' => 8,
    'sender_email' => 'raishivamrai837@gmail.com',
    'sender_name' => 'Shivam Rai',
    'subject' => 'Billing inquiry for subscription renewal (#108)',
    'body' => 'Hello support team,

I am facing an issue regarding: Billing inquiry for subscription renewal (#108). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'billing',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-06T17:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  8 => 
  array (
    'id' => 9,
    'sender_email' => 'rayrb.1234@gmail.com',
    'sender_name' => 'Rajnish Ray',
    'subject' => 'Bug report: Page layout distorted on mobile (#109)',
    'body' => 'Hello support team,

I am facing an issue regarding: Bug report: Page layout distorted on mobile (#109). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'technical support',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-07T15:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  9 => 
  array (
    'id' => 10,
    'sender_email' => 'sarah.connor@example.com',
    'sender_name' => 'Sarah Connor',
    'subject' => 'Feature request: Dark mode toggle (#110)',
    'body' => 'Hello support team,

I am facing an issue regarding: Feature request: Dark mode toggle (#110). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'bug report',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-08T13:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  10 => 
  array (
    'id' => 11,
    'sender_email' => 'kundanrai8102002@gmail.com',
    'sender_name' => 'Kundan Rai',
    'subject' => 'Account deletion request (#111)',
    'body' => 'Hello support team,

I am facing an issue regarding: Account deletion request (#111). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'refund request',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-09T11:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  11 => 
  array (
    'id' => 12,
    'sender_email' => 'rajatdiamondn@gmail.com',
    'sender_name' => 'Rajat Nishad',
    'subject' => 'Payment gateway failed with error 500 (#112)',
    'body' => 'Hello support team,

I am facing an issue regarding: Payment gateway failed with error 500 (#112). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'account',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-10T09:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  12 => 
  array (
    'id' => 13,
    'sender_email' => 'raishivamrai837@gmail.com',
    'sender_name' => 'Shivam Rai',
    'subject' => 'Unable to update profile picture (#113)',
    'body' => 'Hello support team,

I am facing an issue regarding: Unable to update profile picture (#113). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'general question',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-11T07:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  13 => 
  array (
    'id' => 14,
    'sender_email' => 'rayrb.1234@gmail.com',
    'sender_name' => 'Rajnish Ray',
    'subject' => 'Password reset link not received (#114)',
    'body' => 'Hello support team,

I am facing an issue regarding: Password reset link not received (#114). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'technical question',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-07-29T05:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  14 => 
  array (
    'id' => 15,
    'sender_email' => 'sarah.connor@example.com',
    'sender_name' => 'Sarah Connor',
    'subject' => 'Invoice generation error (#115)',
    'body' => 'Hello support team,

I am facing an issue regarding: Invoice generation error (#115). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'feature request',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-07-30T03:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  15 => 
  array (
    'id' => 16,
    'sender_email' => 'kundanrai8102002@gmail.com',
    'sender_name' => 'Kundan Rai',
    'subject' => 'Payment done but bill is still pending (#116)',
    'body' => 'Hello support team,

I am facing an issue regarding: Payment done but bill is still pending (#116). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'billing',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-07-31T01:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  16 => 
  array (
    'id' => 17,
    'sender_email' => 'rajatdiamondn@gmail.com',
    'sender_name' => 'Rajat Nishad',
    'subject' => 'In your site I have face some glitches (#117)',
    'body' => 'Hello support team,

I am facing an issue regarding: In your site I have face some glitches (#117). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'technical support',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-07-31T23:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  17 => 
  array (
    'id' => 18,
    'sender_email' => 'raishivamrai837@gmail.com',
    'sender_name' => 'Shivam Rai',
    'subject' => 'Test for attachments (#118)',
    'body' => 'Hello support team,

I am facing an issue regarding: Test for attachments (#118). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'bug report',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-01T21:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  18 => 
  array (
    'id' => 19,
    'sender_email' => 'rayrb.1234@gmail.com',
    'sender_name' => 'Rajnish Ray',
    'subject' => 'General issue with account login (#119)',
    'body' => 'Hello support team,

I am facing an issue regarding: General issue with account login (#119). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'refund request',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-02T19:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  19 => 
  array (
    'id' => 20,
    'sender_email' => 'sarah.connor@example.com',
    'sender_name' => 'Sarah Connor',
    'subject' => 'Refund request for order #8492 (#120)',
    'body' => 'Hello support team,

I am facing an issue regarding: Refund request for order #8492 (#120). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'account',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-03T17:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  20 => 
  array (
    'id' => 21,
    'sender_email' => 'kundanrai8102002@gmail.com',
    'sender_name' => 'Kundan Rai',
    'subject' => 'Server connection timeout during checkout (#121)',
    'body' => 'Hello support team,

I am facing an issue regarding: Server connection timeout during checkout (#121). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'general question',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-04T15:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  21 => 
  array (
    'id' => 22,
    'sender_email' => 'rajatdiamondn@gmail.com',
    'sender_name' => 'Rajat Nishad',
    'subject' => 'Technical Question regarding API authentication (#122)',
    'body' => 'Hello support team,

I am facing an issue regarding: Technical Question regarding API authentication (#122). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'technical question',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-05T13:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  22 => 
  array (
    'id' => 23,
    'sender_email' => 'raishivamrai837@gmail.com',
    'sender_name' => 'Shivam Rai',
    'subject' => 'Billing inquiry for subscription renewal (#123)',
    'body' => 'Hello support team,

I am facing an issue regarding: Billing inquiry for subscription renewal (#123). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'feature request',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-06T11:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  23 => 
  array (
    'id' => 24,
    'sender_email' => 'rayrb.1234@gmail.com',
    'sender_name' => 'Rajnish Ray',
    'subject' => 'Bug report: Page layout distorted on mobile (#124)',
    'body' => 'Hello support team,

I am facing an issue regarding: Bug report: Page layout distorted on mobile (#124). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'billing',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-07T09:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  24 => 
  array (
    'id' => 25,
    'sender_email' => 'sarah.connor@example.com',
    'sender_name' => 'Sarah Connor',
    'subject' => 'Feature request: Dark mode toggle (#125)',
    'body' => 'Hello support team,

I am facing an issue regarding: Feature request: Dark mode toggle (#125). Please assist me at your earliest convenience.',
    'status' => 'resolved',
    'category' => 'technical support',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => '2026-08-08T07:56:27.000000Z',
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  25 => 
  array (
    'id' => 26,
    'sender_email' => 'kundanrai8102002@gmail.com',
    'sender_name' => 'Kundan Rai',
    'subject' => 'Account deletion request (#126)',
    'body' => 'Hello support team,

I am facing an issue regarding: Account deletion request (#126). Please assist me at your earliest convenience.',
    'status' => 'open',
    'category' => 'bug report',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => NULL,
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  26 => 
  array (
    'id' => 27,
    'sender_email' => 'rajatdiamondn@gmail.com',
    'sender_name' => 'Rajat Nishad',
    'subject' => 'Payment gateway failed with error 500 (#127)',
    'body' => 'Hello support team,

I am facing an issue regarding: Payment gateway failed with error 500 (#127). Please assist me at your earliest convenience.',
    'status' => 'open',
    'category' => 'refund request',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => NULL,
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  27 => 
  array (
    'id' => 28,
    'sender_email' => 'raishivamrai837@gmail.com',
    'sender_name' => 'Shivam Rai',
    'subject' => 'Unable to update profile picture (#128)',
    'body' => 'Hello support team,

I am facing an issue regarding: Unable to update profile picture (#128). Please assist me at your earliest convenience.',
    'status' => 'open',
    'category' => 'account',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => NULL,
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  28 => 
  array (
    'id' => 29,
    'sender_email' => 'rayrb.1234@gmail.com',
    'sender_name' => 'Rajnish Ray',
    'subject' => 'Password reset link not received (#129)',
    'body' => 'Hello support team,

I am facing an issue regarding: Password reset link not received (#129). Please assist me at your earliest convenience.',
    'status' => 'open',
    'category' => 'general question',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => NULL,
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  29 => 
  array (
    'id' => 30,
    'sender_email' => 'sarah.connor@example.com',
    'sender_name' => 'Sarah Connor',
    'subject' => 'Invoice generation error (#130)',
    'body' => 'Hello support team,

I am facing an issue regarding: Invoice generation error (#130). Please assist me at your earliest convenience.',
    'status' => 'open',
    'category' => 'technical question',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => NULL,
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  30 => 
  array (
    'id' => 31,
    'sender_email' => 'kundanrai8102002@gmail.com',
    'sender_name' => 'Kundan Rai',
    'subject' => 'Payment done but bill is still pending (#131)',
    'body' => 'Hello support team,

I am facing an issue regarding: Payment done but bill is still pending (#131). Please assist me at your earliest convenience.',
    'status' => 'open',
    'category' => 'feature request',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:28.000000Z',
    'updated_at' => '2026-08-13T09:51:28.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => NULL,
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  31 => 
  array (
    'id' => 32,
    'sender_email' => 'rajatdiamondn@gmail.com',
    'sender_name' => 'Rajat Nishad',
    'subject' => 'In your site I have face some glitches (#132)',
    'body' => 'Hello support team,

I am facing an issue regarding: In your site I have face some glitches (#132). Please assist me at your earliest convenience.',
    'status' => 'open',
    'category' => 'billing',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:28.000000Z',
    'updated_at' => '2026-08-13T09:51:28.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => NULL,
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  32 => 
  array (
    'id' => 33,
    'sender_email' => 'raishivamrai837@gmail.com',
    'sender_name' => 'Shivam Rai',
    'subject' => 'Test for attachments (#133)',
    'body' => 'Hello support team,

I am facing an issue regarding: Test for attachments (#133). Please assist me at your earliest convenience.',
    'status' => 'processing',
    'category' => 'technical support',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:28.000000Z',
    'updated_at' => '2026-08-13T09:51:28.000000Z',
    'priority' => 'high',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => NULL,
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
  33 => 
  array (
    'id' => 34,
    'sender_email' => 'rayrb.1234@gmail.com',
    'sender_name' => 'Rajnish Ray',
    'subject' => 'General issue with account login (#134)',
    'body' => 'Hello support team,

I am facing an issue regarding: General issue with account login (#134). Please assist me at your earliest convenience.',
    'status' => 'processing',
    'category' => 'bug report',
    'assigned_agent_id' => NULL,
    'created_at' => '2026-08-13T09:51:28.000000Z',
    'updated_at' => '2026-08-13T09:51:28.000000Z',
    'priority' => 'medium',
    'ai_summary' => NULL,
    'category_confidence' => NULL,
    'classified_at' => NULL,
    'ai_resolved_at' => NULL,
    'resolved_at' => NULL,
    'message_id' => NULL,
    'body_html' => NULL,
  ),
);
        $replies = array (
  0 => 
  array (
    'id' => 1,
    'ticket_id' => 1,
    'user_id' => 4,
    'body' => 'Hello support team,

I am facing an issue regarding: Payment done but bill is still pending (#101). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Payment done but bill is still pending (#101)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  1 => 
  array (
    'id' => 2,
    'ticket_id' => 1,
    'user_id' => 3,
    'body' => 'Hi Kundan Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Kundan Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  2 => 
  array (
    'id' => 3,
    'ticket_id' => 2,
    'user_id' => 5,
    'body' => 'Hello support team,

I am facing an issue regarding: In your site I have face some glitches (#102). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>In your site I have face some glitches (#102)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  3 => 
  array (
    'id' => 4,
    'ticket_id' => 2,
    'user_id' => 3,
    'body' => 'Hi Rajat Nishad,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajat Nishad,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  4 => 
  array (
    'id' => 5,
    'ticket_id' => 3,
    'user_id' => 6,
    'body' => 'Hello support team,

I am facing an issue regarding: Test for attachments (#103). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Test for attachments (#103)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  5 => 
  array (
    'id' => 6,
    'ticket_id' => 3,
    'user_id' => 3,
    'body' => 'Hi Shivam Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Shivam Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  6 => 
  array (
    'id' => 7,
    'ticket_id' => 4,
    'user_id' => 7,
    'body' => 'Hello support team,

I am facing an issue regarding: General issue with account login (#104). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>General issue with account login (#104)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  7 => 
  array (
    'id' => 8,
    'ticket_id' => 4,
    'user_id' => 3,
    'body' => 'Hi Rajnish Ray,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajnish Ray,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  8 => 
  array (
    'id' => 9,
    'ticket_id' => 5,
    'user_id' => 8,
    'body' => 'Hello support team,

I am facing an issue regarding: Refund request for order #8492 (#105). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Refund request for order #8492 (#105)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  9 => 
  array (
    'id' => 10,
    'ticket_id' => 5,
    'user_id' => 3,
    'body' => 'Hi Sarah Connor,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Sarah Connor,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  10 => 
  array (
    'id' => 11,
    'ticket_id' => 6,
    'user_id' => 4,
    'body' => 'Hello support team,

I am facing an issue regarding: Server connection timeout during checkout (#106). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Server connection timeout during checkout (#106)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  11 => 
  array (
    'id' => 12,
    'ticket_id' => 6,
    'user_id' => 3,
    'body' => 'Hi Kundan Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Kundan Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  12 => 
  array (
    'id' => 13,
    'ticket_id' => 7,
    'user_id' => 5,
    'body' => 'Hello support team,

I am facing an issue regarding: Technical Question regarding API authentication (#107). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Technical Question regarding API authentication (#107)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  13 => 
  array (
    'id' => 14,
    'ticket_id' => 7,
    'user_id' => 3,
    'body' => 'Hi Rajat Nishad,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajat Nishad,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  14 => 
  array (
    'id' => 15,
    'ticket_id' => 8,
    'user_id' => 6,
    'body' => 'Hello support team,

I am facing an issue regarding: Billing inquiry for subscription renewal (#108). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Billing inquiry for subscription renewal (#108)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  15 => 
  array (
    'id' => 16,
    'ticket_id' => 8,
    'user_id' => 3,
    'body' => 'Hi Shivam Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Shivam Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  16 => 
  array (
    'id' => 17,
    'ticket_id' => 9,
    'user_id' => 7,
    'body' => 'Hello support team,

I am facing an issue regarding: Bug report: Page layout distorted on mobile (#109). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Bug report: Page layout distorted on mobile (#109)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  17 => 
  array (
    'id' => 18,
    'ticket_id' => 9,
    'user_id' => 3,
    'body' => 'Hi Rajnish Ray,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajnish Ray,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  18 => 
  array (
    'id' => 19,
    'ticket_id' => 10,
    'user_id' => 8,
    'body' => 'Hello support team,

I am facing an issue regarding: Feature request: Dark mode toggle (#110). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Feature request: Dark mode toggle (#110)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  19 => 
  array (
    'id' => 20,
    'ticket_id' => 10,
    'user_id' => 3,
    'body' => 'Hi Sarah Connor,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Sarah Connor,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  20 => 
  array (
    'id' => 21,
    'ticket_id' => 11,
    'user_id' => 4,
    'body' => 'Hello support team,

I am facing an issue regarding: Account deletion request (#111). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Account deletion request (#111)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  21 => 
  array (
    'id' => 22,
    'ticket_id' => 11,
    'user_id' => 3,
    'body' => 'Hi Kundan Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Kundan Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  22 => 
  array (
    'id' => 23,
    'ticket_id' => 12,
    'user_id' => 5,
    'body' => 'Hello support team,

I am facing an issue regarding: Payment gateway failed with error 500 (#112). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Payment gateway failed with error 500 (#112)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  23 => 
  array (
    'id' => 24,
    'ticket_id' => 12,
    'user_id' => 3,
    'body' => 'Hi Rajat Nishad,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajat Nishad,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  24 => 
  array (
    'id' => 25,
    'ticket_id' => 13,
    'user_id' => 6,
    'body' => 'Hello support team,

I am facing an issue regarding: Unable to update profile picture (#113). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Unable to update profile picture (#113)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  25 => 
  array (
    'id' => 26,
    'ticket_id' => 13,
    'user_id' => 3,
    'body' => 'Hi Shivam Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Shivam Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  26 => 
  array (
    'id' => 27,
    'ticket_id' => 14,
    'user_id' => 7,
    'body' => 'Hello support team,

I am facing an issue regarding: Password reset link not received (#114). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Password reset link not received (#114)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  27 => 
  array (
    'id' => 28,
    'ticket_id' => 14,
    'user_id' => 3,
    'body' => 'Hi Rajnish Ray,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajnish Ray,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  28 => 
  array (
    'id' => 29,
    'ticket_id' => 15,
    'user_id' => 8,
    'body' => 'Hello support team,

I am facing an issue regarding: Invoice generation error (#115). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Invoice generation error (#115)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  29 => 
  array (
    'id' => 30,
    'ticket_id' => 15,
    'user_id' => 3,
    'body' => 'Hi Sarah Connor,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Sarah Connor,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  30 => 
  array (
    'id' => 31,
    'ticket_id' => 16,
    'user_id' => 4,
    'body' => 'Hello support team,

I am facing an issue regarding: Payment done but bill is still pending (#116). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Payment done but bill is still pending (#116)</strong>. Please assist me.</p>',
    'attachment_path' => 'attachments/checkout_error_screenshot.png',
    'attachment_name' => 'checkout_error_screenshot.png',
    'attachment_mime' => 'image/png',
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'completed',
  ),
  31 => 
  array (
    'id' => 32,
    'ticket_id' => 16,
    'user_id' => 3,
    'body' => 'Hi Kundan Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Kundan Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  32 => 
  array (
    'id' => 33,
    'ticket_id' => 17,
    'user_id' => 5,
    'body' => 'Hello support team,

I am facing an issue regarding: In your site I have face some glitches (#117). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>In your site I have face some glitches (#117)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  33 => 
  array (
    'id' => 34,
    'ticket_id' => 17,
    'user_id' => 3,
    'body' => 'Hi Rajat Nishad,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajat Nishad,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  34 => 
  array (
    'id' => 35,
    'ticket_id' => 18,
    'user_id' => 6,
    'body' => 'Hello support team,

I am facing an issue regarding: Test for attachments (#118). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Test for attachments (#118)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  35 => 
  array (
    'id' => 36,
    'ticket_id' => 18,
    'user_id' => 3,
    'body' => 'Hi Shivam Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Shivam Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  36 => 
  array (
    'id' => 37,
    'ticket_id' => 19,
    'user_id' => 7,
    'body' => 'Hello support team,

I am facing an issue regarding: General issue with account login (#119). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>General issue with account login (#119)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  37 => 
  array (
    'id' => 38,
    'ticket_id' => 19,
    'user_id' => 3,
    'body' => 'Hi Rajnish Ray,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajnish Ray,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  38 => 
  array (
    'id' => 39,
    'ticket_id' => 20,
    'user_id' => 8,
    'body' => 'Hello support team,

I am facing an issue regarding: Refund request for order #8492 (#120). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Refund request for order #8492 (#120)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  39 => 
  array (
    'id' => 40,
    'ticket_id' => 20,
    'user_id' => 3,
    'body' => 'Hi Sarah Connor,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Sarah Connor,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  40 => 
  array (
    'id' => 41,
    'ticket_id' => 21,
    'user_id' => 4,
    'body' => 'Hello support team,

I am facing an issue regarding: Server connection timeout during checkout (#121). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Server connection timeout during checkout (#121)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  41 => 
  array (
    'id' => 42,
    'ticket_id' => 21,
    'user_id' => 3,
    'body' => 'Hi Kundan Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Kundan Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  42 => 
  array (
    'id' => 43,
    'ticket_id' => 22,
    'user_id' => 5,
    'body' => 'Hello support team,

I am facing an issue regarding: Technical Question regarding API authentication (#122). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Technical Question regarding API authentication (#122)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  43 => 
  array (
    'id' => 44,
    'ticket_id' => 22,
    'user_id' => 3,
    'body' => 'Hi Rajat Nishad,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajat Nishad,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  44 => 
  array (
    'id' => 45,
    'ticket_id' => 23,
    'user_id' => 6,
    'body' => 'Hello support team,

I am facing an issue regarding: Billing inquiry for subscription renewal (#123). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Billing inquiry for subscription renewal (#123)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  45 => 
  array (
    'id' => 46,
    'ticket_id' => 23,
    'user_id' => 3,
    'body' => 'Hi Shivam Rai,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Shivam Rai,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  46 => 
  array (
    'id' => 47,
    'ticket_id' => 24,
    'user_id' => 7,
    'body' => 'Hello support team,

I am facing an issue regarding: Bug report: Page layout distorted on mobile (#124). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Bug report: Page layout distorted on mobile (#124)</strong>. Please assist me.</p>',
    'attachment_path' => 'attachments/checkout_error_screenshot.png',
    'attachment_name' => 'checkout_error_screenshot.png',
    'attachment_mime' => 'image/png',
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'completed',
  ),
  47 => 
  array (
    'id' => 48,
    'ticket_id' => 24,
    'user_id' => 3,
    'body' => 'Hi Rajnish Ray,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Rajnish Ray,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  48 => 
  array (
    'id' => 49,
    'ticket_id' => 25,
    'user_id' => 8,
    'body' => 'Hello support team,

I am facing an issue regarding: Feature request: Dark mode toggle (#125). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Feature request: Dark mode toggle (#125)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  49 => 
  array (
    'id' => 50,
    'ticket_id' => 25,
    'user_id' => 3,
    'body' => 'Hi Sarah Connor,

Our AI Assistant has automatically resolved your query. Thank you for contacting support!',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'agent',
    'body_html' => '<p>Hi Sarah Connor,</p><p>Our AI Assistant has automatically resolved your query. Thank you for contacting support!</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  50 => 
  array (
    'id' => 51,
    'ticket_id' => 26,
    'user_id' => 4,
    'body' => 'Hello support team,

I am facing an issue regarding: Account deletion request (#126). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Account deletion request (#126)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  51 => 
  array (
    'id' => 52,
    'ticket_id' => 27,
    'user_id' => 5,
    'body' => 'Hello support team,

I am facing an issue regarding: Payment gateway failed with error 500 (#127). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Payment gateway failed with error 500 (#127)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  52 => 
  array (
    'id' => 53,
    'ticket_id' => 28,
    'user_id' => 6,
    'body' => 'Hello support team,

I am facing an issue regarding: Unable to update profile picture (#128). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Unable to update profile picture (#128)</strong>. Please assist me.</p>',
    'attachment_path' => 'attachments/checkout_error_screenshot.png',
    'attachment_name' => 'checkout_error_screenshot.png',
    'attachment_mime' => 'image/png',
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'completed',
  ),
  53 => 
  array (
    'id' => 54,
    'ticket_id' => 29,
    'user_id' => 7,
    'body' => 'Hello support team,

I am facing an issue regarding: Password reset link not received (#129). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:27.000000Z',
    'updated_at' => '2026-08-13T09:51:27.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Password reset link not received (#129)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  54 => 
  array (
    'id' => 55,
    'ticket_id' => 30,
    'user_id' => 8,
    'body' => 'Hello support team,

I am facing an issue regarding: Invoice generation error (#130). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:28.000000Z',
    'updated_at' => '2026-08-13T09:51:28.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Invoice generation error (#130)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  55 => 
  array (
    'id' => 56,
    'ticket_id' => 31,
    'user_id' => 4,
    'body' => 'Hello support team,

I am facing an issue regarding: Payment done but bill is still pending (#131). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:28.000000Z',
    'updated_at' => '2026-08-13T09:51:28.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Payment done but bill is still pending (#131)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  56 => 
  array (
    'id' => 57,
    'ticket_id' => 32,
    'user_id' => 5,
    'body' => 'Hello support team,

I am facing an issue regarding: In your site I have face some glitches (#132). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:28.000000Z',
    'updated_at' => '2026-08-13T09:51:28.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>In your site I have face some glitches (#132)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
  57 => 
  array (
    'id' => 58,
    'ticket_id' => 33,
    'user_id' => 6,
    'body' => 'Hello support team,

I am facing an issue regarding: Test for attachments (#133). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:28.000000Z',
    'updated_at' => '2026-08-13T09:51:28.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>Test for attachments (#133)</strong>. Please assist me.</p>',
    'attachment_path' => 'attachments/checkout_error_screenshot.png',
    'attachment_name' => 'checkout_error_screenshot.png',
    'attachment_mime' => 'image/png',
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'completed',
  ),
  58 => 
  array (
    'id' => 59,
    'ticket_id' => 34,
    'user_id' => 7,
    'body' => 'Hello support team,

I am facing an issue regarding: General issue with account login (#134). Please assist me at your earliest convenience.',
    'created_at' => '2026-08-13T09:51:28.000000Z',
    'updated_at' => '2026-08-13T09:51:28.000000Z',
    'sender_type' => 'customer',
    'body_html' => '<p>Hello support team,</p><p>I am facing an issue regarding: <strong>General issue with account login (#134)</strong>. Please assist me.</p>',
    'attachment_path' => NULL,
    'attachment_name' => NULL,
    'attachment_mime' => NULL,
    'transfer_reason' => NULL,
    'attachment_optimized_path' => NULL,
    'attachment_processing_status' => 'none',
  ),
);
        $notifications = array (
);

        DB::table('app_notifications')->truncate();
        DB::table('ticket_replies')->truncate();
        DB::table('tickets')->truncate();
        DB::table('users')->truncate();

        foreach ($users as $user) {
            $data = array_intersect_key($user, array_flip($userColumns));
            DB::table('users')->insert($data);
        }

        foreach ($tickets as $ticket) {
            $data = array_intersect_key($ticket, array_flip($ticketColumns));
            DB::table('tickets')->insert($data);
        }

        foreach ($replies as $reply) {
            $data = array_intersect_key($reply, array_flip($replyColumns));
            DB::table('ticket_replies')->insert($data);
        }

        foreach ($notifications as $notif) {
            $data = array_intersect_key($notif, array_flip($notifColumns));
            DB::table('app_notifications')->insert($data);
        }

        Schema::enableForeignKeyConstraints();
    }
}
