<?php

namespace App\Enums;

/**
 * Enum: SenderType
 *
 * Identifies who authored a TicketReply — an internal support agent/admin
 * acting on behalf of the support team, or the original customer who raised
 * the ticket.
 *
 * This distinction drives:
 *   • Visual layout  — agent replies align left (internal blue thread);
 *                      customer replies align right (warm amber/orange thread).
 *   • Business logic — only authenticated app users can create Agent replies;
 *                      Customer replies are reserved for future inbound-email
 *                      webhooks or customer-portal integrations.
 *   • Analytics      — makes it trivial to filter/count by sender type
 *                      without touching the users table.
 *
 * Values are lowercase strings so they store cleanly in the DB and are
 * human-readable in raw SQL queries.
 */
enum SenderType: string
{
    /** A reply posted by an authenticated agent or admin through the portal. */
    case Agent    = 'agent';

    /** A reply that originated from the customer (e.g. via inbound email). */
    case Customer = 'customer';

    /** A reply automatically generated by the AI system. */
    case System   = 'system';

    /**
     * Returns a short, human-readable label for display in the UI.
     */
    public function label(): string
    {
        return match ($this) {
            self::Agent    => 'Agent',
            self::Customer => 'Customer',
            self::System   => 'AI/System',
        };
    }

    /**
     * Returns true when the sender is the customer side of the conversation.
     * Convenience helper so views can write $reply->sender_type->isCustomer()
     * instead of a comparison.
     */
    public function isCustomer(): bool
    {
        return $this === self::Customer;
    }

    /**
     * Returns true when the sender is an internal agent or admin.
     */
    public function isAgent(): bool
    {
        return $this === self::Agent;
    }

    /**
     * Returns true when the sender is the AI/System.
     */
    public function isSystem(): bool
    {
        return $this === self::System;
    }
}
